In [8]:
import pandas as pd

# Creating the raw dataset using a dictionary of lists
data = {
    "Name": ["Rahul", "Priya", "Amit", "Anuj"],
    "Age": [25, 30, 28, 35],
    "Department": ["HR", "IT", "Finance", "IT"],
    "Salary": [30000, 50000, 45000, 60000]
}

# Converting to a Pandas DataFrame
df = pd.DataFrame(data)

print("Employee DataFrame:")
display(df)

Employee DataFrame:

    Name  Age Department  Salary
0  Rahul   25         HR   30000
1  Priya   30         IT   50000
2   Amit   28    Finance   45000
3   Anuj   35         IT   60000

In [11]:
# Task 2: Show first 2 rows
first_two_rows = df.head(2)

print("First 2 Rows:")
display(first_two_rows)

First 2 Rows:

    Name  Age Department  Salary
0  Rahul   25         HR   30000
1  Priya   30         IT   50000

In [12]:
# Task 3: Show summary statistics
summary_stats = df.describe()

print("Summary Statistics:")
display(summary_stats)

Summary Statistics:

             Age   Salary
count   4.000000      4.0
mean   29.500000  46250.0
std     4.203173  12500.0
min    25.000000  30000.0
25%    27.250000  41250.0
50%    29.000000  47500.0
75%    31.250000  52500.0
max    35.000000  60000.0

In [13]:
# Task 4: Display only IT employees
it_employees = df[df["Department"] == "IT"]

print("IT Department Employees:")
display(it_employees)

IT Department Employees:

    Name  Age Department  Salary
1  Priya   30         IT   50000
3   Anuj   35         IT   60000

In [14]:
# Task 5: Add new column: Bonus = Salary * 0.10
df["Bonus"] = df["Salary"] * 0.10

print("DataFrame with 10% Bonus Column:")
display(df)

DataFrame with 10% Bonus Column:

    Name  Age Department  Salary   Bonus
0  Rahul   25         HR   30000  3000.0
1  Priya   30         IT   50000  5000.0
2   Amit   28    Finance   45000  4500.0
3   Anuj   35         IT   60000  6000.0