In [3]:
import pandas as pd

# Task 1: Create dataset and Load into Pandas
data = {
    'Name': ['Rahul', 'Priya', 'Siri', 'Anuj'],
    'Marks': [70, 80, 90, 60],
    'Hours Studied': [2, 3, 5, 1]
}

df = pd.DataFrame(data)
display(df)

    Name  Marks  Hours Studied
0  Rahul     70              2
1  Priya     80              3
2   Siri     90              5
3   Anuj     60              1

In [5]:

# Task 2: Add Performance column (Pass if Marks > 65 else Fail)
df['Performance'] = df['Marks'].apply(lambda x: 'Pass' if x > 65 else 'Fail')

print("Student DataFrame:")
display(df)

Student DataFrame:

    Name  Marks  Hours Studied Performance
0  Rahul     70              2        Pass
1  Priya     80              3        Pass
2   Siri     90              5        Pass
3   Anuj     60              1        Fail