In [1]:
import pandas as pd
import numpy as np

# Create the dataset with missing values
data = {
    'Name': ['Rahul', 'Priya', 'Anuj'],
    'Age': [25, np.nan, 29],
    'Salary': [30000, 40000, np.nan]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
df

Original DataFrame:

    Name   Age   Salary
0  Rahul  25.0  30000.0
1  Priya   NaN  40000.0
2   Anuj  29.0      NaN

In [3]:
# Task 1: Detect missing values
# .isna() returns True for missing values, and .sum() counts the True values per column
missing_counts = df.isna().sum()

print("Missing Values Per Column:")
print(missing_counts)

print("\nBoolean map of missing values:")
display(df.isna())

Missing Values Per Column:
Name      0
Age       1
Salary    1
dtype: int64

Boolean map of missing values:

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True

In [4]:
# Task 2: Replace missing Age with mean
# Calculate the mean age from the existing valid data
mean_age = df["Age"].mean()
print(f"Calculated Mean Age: {mean_age}\n")

# Use .fillna() to replace only the NaN values in the Age column
df["Age"] = df["Age"].fillna(mean_age)

print("DataFrame after Age imputation:")
display(df)

Calculated Mean Age: 27.0

DataFrame after Age imputation:

    Name   Age   Salary
0  Rahul  25.0  30000.0
1  Priya  27.0  40000.0
2   Anuj  29.0      NaN

In [5]:
# Task 3: Replace missing Salary with 0
df["Salary"] = df["Salary"].fillna(0)

print("Final Cleaned DataFrame:")
display(df)

Final Cleaned DataFrame:

    Name   Age   Salary
0  Rahul  25.0  30000.0
1  Priya  27.0  40000.0
2   Anuj  29.0      0.0